#!/bin/dash

# girt-show: prints the contents of the specified filename as of the specified commit.

# Raises error if there isn't a girt repo
if ! test -d ".girt"
then
    echo "girt-show: error: girt repository directory .girt not found"
    exit 1
fi

# Exits if there aren't any arguments
if test $# -ne 1
then
    echo "usage: girt-show <commit>:<filename>"
    exit 1
fi

# Grabs commit number
commit_number=$(echo $1 | cut -d':' -f1)

# Grabs filename
filename=$(echo $1 | cut -d':' -f2)

# Aren't any specified commit
no_number=$(echo $1 | sed "s/[a-zA-Z.]//g")

if test "$no_number" = ":"
then
    if test -e ".girt/index/$filename"
    then
        cat ".girt/index/$filename"
        exit 1
    else
        echo "girt-show: error: '$filename' not found in index"
        exit 1
    fi

fi

if ! test -d ".girt/master/commits/$commit_number"
then
    echo "girt-show: error: unknown commit '$commit_number'"
    exit 1
else
    if ! test -e ".girt/master/commits/$commit_number/$filename"
    then
        echo "girt-show: error: '$filename' not found in commit $commit_number"
        exit 1
    else
        cat ".girt/master/commits/$commit_number/$filename"
    fi
fi


